/*
 * Copyright 2026 AzoraLabs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.azora.lang.idea.project

import com.intellij.openapi.application.ApplicationManager
import com.intellij.openapi.components.*

/**
 * Application-level persistent service storing the Azora SDK location.
 *
 * Persisted to `AzoraSdkSettings.xml` in the IDE's config directory.
 * The SDK path is used by run configurations, the build system, and
 * the project wizard to locate the `azora` and `azora-build` binaries.
 */
@Service(Service.Level.APP)
@State(
    name = "AzoraSdkSettings",
    storages = [Storage("AzoraSdkSettings.xml")]
)
class AzoraSdkSettings : SimplePersistentStateComponent<AzoraSdkSettingsState>(AzoraSdkSettingsState()) {

    /**
     * Returns the resolved SDK path, expanding `~` to the user's home directory.
     *
     * Falls back to [defaultSdkPath] (`~/.azoralang`) if no path has been configured.
     *
     * @return the absolute filesystem path to the Azora SDK root.
     */
    fun sdkPath(): String {
        val path = state.langPath
        val resolved = if (path.isNullOrEmpty()) defaultSdkPath() else path
        return if (resolved.startsWith("~/"))
            System.getProperty("user.home") + resolved.substring(1)
        else resolved
    }

    companion object {
        /**
         * Returns the application-level [AzoraSdkSettings] service instance.
         *
         * @return the singleton settings service.
         */
        fun getInstance(): AzoraSdkSettings =
            ApplicationManager.getApplication().getService(AzoraSdkSettings::class.java)
    }
}

/**
 * Persistent state backing [AzoraSdkSettings].
 *
 * Contains the user-configured SDK path, defaulting to `~/.azoralang`.
 */
class AzoraSdkSettingsState : BaseState() {
    /** The filesystem path to the Azora SDK root directory. */
    var langPath by string(defaultSdkPath())
}

/**
 * Returns the default Azora SDK path (`~/.azoralang`).
 *
 * @return the absolute default path using the current user's home directory.
 */
private fun defaultSdkPath(): String =
    System.getProperty("user.home") + "/.azoralang"

/**
 * Converts a string to `snake_case`.
 *
 * Handles camelCase (`"myApp"` -> `"my_app"`), PascalCase (`"MyApp"` -> `"my_app"`),
 * and kebab-case (`"my-app"` -> `"my_app"`).
 *
 * @return the snake_case version of this string.
 */
fun String.toSnakeCase(): String =
    replace(Regex("([a-z])([A-Z])")) { "${it.groupValues[1]}_${it.groupValues[2]}" }
        .replace(Regex("[\\s\\-]+"), "_")
        .lowercase()

// Project manifests are generated by `AzoraProjectScaffolder`, which writes
// AZON (`package.azon` / `workspace.azon`) rather than the legacy TOML form.
